## Reformat of annotation of ITR-seq peaks
ReformatPeakAnno <- function(ftxt) {
  ## ftxt   A tab-delimited text file generated by the ITR-seq pipeline; including peak information and original annotation
  
  ## Read in original table
  peak <- read.csv(ftxt, sep='\t', header = TRUE, stringsAsFactors = FALSE);
  
  if (nrow(peak) == 0) { # Return NULL if no peak 
    NULL; 
  } else {
    ## Unique peak ID
    id <- sub('^.+Name=', '', sub(';ReadCount=.+$', '', peak$name));
    
    ## Basic peak information
    ann0 <- data.frame(Peak=id, Chrom=peak$chrom, Start=peak$start, End=peak$end, stringsAsFactors = FALSE, row.names = 1:length(id));
    ann0$Read <- as.integer(sub('^.+ReadCount=', '', sub(';ReadStrandCounts=.+$', '', peak$name)));
    ann0$Score <- peak$score;
    
    ## Ensembl annotation only
    olp <- strsplit(peak$overlap_details, ' // ');
    olp <- lapply(olp, function(o) o[grep('Source=ensembl', o)]);
    
    ###########################################################################################
    ## Gene-level annotation
    olp1 <- strsplit(sapply(olp, function(o) o[1]), ';');
    
    ## Required annotation fields
    typ1 <- sub('^Type=', '', sapply(olp1, function(o) as.character(o[grep('^Type=', o)])[1]));
    loc1 <- sub('^Locus=', '', sapply(olp1, function(o) as.character(o[grep('^Locus=', o)])[1]));
    ori1 <- sub('^Orient=', '', sapply(olp1, function(o) as.character(o[grep('^Orient=', o)])[1]));
    gid1 <- sub('^gene_id=', '', sapply(olp1, function(o) as.character(o[grep('^gene_id=', o)])[1]));
    gnm1 <- sub('^Name=', '', sapply(olp1, function(o) as.character(o[grep('^Name=', o)])[1]));
    bio1 <- sub('^biotype=', '', sapply(olp1, function(o) as.character(o[grep('^biotype=', o)])[1]));
    dsc1 <- sub('^description=', '', sapply(olp1, function(o) as.character(o[grep('^description=', o)])[1]));
    dsc1 <- sub(' \\[Source.+$', '', dsc1);
    
    ## Gene TSS/TTS and strand
    str1 <- sub('^.+:', '', loc1);
    loc1 <- sub('^.+:', '', sub(':[+-]$', '', loc1));
    fst1 <- sub('-.+$', '', loc1);
    lst1 <- sub('^.+-', '', loc1);
    tss1 <- fst1;
    tts1 <- lst1;
    tss1[str1=='-'] <- lst1[str1=='-'];
    tts1[str1=='-'] <- fst1[str1=='-'];
    
    ## Gene annotation table
    ann1 <- cbind(Gene_ID=gid1, Gene_Name=gnm1, Gene_Biotype=bio1, Gene_Description=dsc1); 
    ann1[is.na(ann1)] <- '';
    ann1 <- data.frame(ann1, stringsAsFactors = FALSE);
    ann1$Gene_TSS <- as.integer(tss1);
    ann1$Gene_TTS <- as.integer(tts1);
    ann1$Gene_Strand <- str1;
    ann1$Gene_Overlap <- as.integer(ann0$Start<=lst1 & ann0$End>=fst1);
    
    ## Distance from peak to TSS
    d1 <- (ann0$Start+1) - ann1$Gene_TSS; # First base of peak to TSS
    d2 <- ann0$End - ann1$Gene_TSS; # Last base of peak to TSS
    d0 <- d1; # Nearest distance; use first base distance by default
    d0[sign(d1)!=sign(d2)] <- 0; # Distance is 0 if TSS is within peak
    d0[sign(d1)==sign(d2) & abs(d1)>abs(d2)] <- d2[sign(d1)==sign(d2) & abs(d1)>abs(d2)]; # When the last base of peak is closer
    d0[ann1$Gene_Strand=='-'] <- -d0[ann1$Gene_Strand=='-']; # Reverse if gene is on the minus strand
    ann1$Dist2TSS <- d0;
    
    ###########################################################################################
    ## Sub-gene-level annotation
    PROMOTER_RANGE <- c(-1000, -1);
    typ2 <- c('CDS', 'five_prime_UTR', 'three_prime_UTR');
    cnt2 <- do.call('cbind', lapply(paste0('Type=', typ2), function(tp) 
      pmin(1, sapply(olp, function(o) length(o[grepl(tp, o) & grepl("Orient=overlap", o)])))));
    prm2 <- as.integer(ann1$Dist2TSS>=min(PROMOTER_RANGE) & ann1$Dist2TSS<=max(PROMOTER_RANGE));
    ann2 <- data.frame(cnt2[, 1], prm2, cnt2[, 2], cnt2[, 3], stringsAsFactors = FALSE);
    ann2 <- cbind(ann2, as.integer(ann1$Gene_Overlap==1), as.integer(ann1$Gene_Overlap==0));
    colnames(ann2) <- c('CDS', 'Promoter', '5UTR', '3UTR', 'Intragenic', 'Intergenic');
    ann2$Representative <- colnames(ann2)[max.col(ann2, ties.method = 'first')];
    
    ###########################################################################################  
    invisible(cbind(ann0, ann1, ann2));
  }
}
